title: Open Source Chess
email: josephhaig@gmail.com
description: >
  Play chess with pull requests
baseurl: ""
url: ""
twitter_username: jrmhaig
github_username:  jrmhaig

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
